config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
  post 'toggle_like', to: 'likes#toggle_like', as: :toggle_like

  resources :comments, only: [:create, :destroy]
  resources :users, only: [:show]

  post "follow", to: 'follows#follow', as: :follow
  delete 'unfollow', to: 'follows#unfollow', as: :unfollow
  delete 'cancel_request', to: 'follows#cancel_request', as: :cancel_request

  post 'accept_follow', to: 'follows#accept_follow', as: :accept_follow
  delete 'decline_follow', to: 'follows#decline_follow', as: :decline_follow
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
  before_create :auto_accept
  belongs_to :followed, class_name: "User", foreign_key: "followed_id"
  belongs_to :follower, class_name: "User", foreign_key: "follower_id"

  def accept
    self.update(accepted: true)
  end

  private
  def auto_accept
    self.accepted = true unless self.followed.private
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness:{scope: :post_id}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  validates :images, presence: true, blob: { content_type: :image }
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_one_attached :profile_pic
  # class_name: "post", foreign_key: "reference_id"
  has_many :likes
  has_many :comments

  # follow_system
  # be_followed
  has_many :accepted_received_requests, -> { where(accepted: true) }, class_name: "Follow", foreign_key: "followed_id"
  has_many :waiting_received_requests, -> { where(accepted: false) }, class_name: "Follow", foreign_key: "followed_id"
  # following_others
  has_many :accepted_sent_requests, -> { where(accepted: true) }, class_name: "Follow", foreign_key: "follower_id"
  has_many :waiting_sent_requests, -> { where(accepted: false) }, class_name: "Follow", foreign_key: "follower_id"

  # follower & following
  has_many :followers, through: :accepted_received_requests, source: :follower
  has_many :followings, through: :accepted_sent_requests, source: :followed
  has_many :waiting_followings, through: :waiting_sent_requests, source: :followed

  def follow(user)
    Follow.create(follower: self, followed: user)
  end

  def unfollow(user)
    self.accepted_sent_requests.find_by(followed: user)&.destroy
  end

  def cancel_request(user)
    self.waiting_sent_requests.find_by(followed: user)&.destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :phone_number, :full_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :phone_number, :full_name, :profile_pic, :bio, :private])

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create]

  def create
    @comment = @post.comments.create(user: current_user, body: params[:comment_body])
    respond_to do |format|
      format.turbo_stream do 
        render turbo_stream: turbo_stream.replace(
          "post#{@post.id}comments",
          partial: "posts/post_comments",
          locals: {post: @post}
        )
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if(@comment.user == current_user)
      @comment.destroy

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.remove(
            "post#{@comment.post_id}ModalComment#{@comment.id}"
          )
        end
      end
    end
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_user, only: [:follow, :unfollow, :cancel_request]
  before_action :set_follow_req, only: [:accept_follow, :decline_follow]
  
  def follow
    current_user.follow(@user)
    redirect_back(fallback_location: root_path)

  end

  def cancel_request
    current_user.cancel_request(@user)
    redirect_back(fallback_location: root_path)
  end

  def unfollow
    current_user.unfollow(@user)
    redirect_back(fallback_location: root_path)
  end


  def accept_follow
    @follow_req.accept
    redirect_back(fallback_location: root_path)
  end

  def decline_follow
    @follow_req.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def set_user
    @user = User.find(params[:user_id])
  end

  def set_follow_req
    @follow_req = Follow.find(params[:follow_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_feeds
  def index
  end

  private
  def set_feeds
    @feeds = Post.where(user: [current_user, current_user.followings].flatten).order(created_at: :desc)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
before_action :set_post

def toggle_like
  if(@like = @post.likes.find_by(user: current_user))
    @like.destroy
  else
    @post.likes.create(user: current_user)
  end

  respond_to do |format|
    format.turbo_stream do
      render turbo_stream: turbo_stream.replace(
        "post#{@post.id}actions",
        partial: "posts/post_action",
        locals: {post: @post}
      )
    end
  end
end










  private
  def set_post
    @post = Post.find(params[:post_id])
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    redirect_to root_path
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { redirect_to root_path, status: :unprocessable_entity, alert: @post.errors.full_messages }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    return if current_user != @post.user
    @post.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :longitude, :lattitude, :user_id, :allow_to_comment, :show_likes, images: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  
  def show
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<!--<%= render "layouts/flash_messages" %> -->
<div class= "d-flex my-5 justify-content-center gap-5">
  <div class= "d-flex flex-column gap-3">
    <%= render 'story/story_list' %>
      <div class = "flex flex-column">
      <% @feeds.each do |p| %>
        <%= render 'posts/post', post: p %>
      <% end %>
      </div>
  </div>
   <%= render 'suggestions/suggestion_list' %>
</div>

app/views/layouts/_flash_messages.html.erb
<% if notice && notice.is_a?(Array) %>
  <% notice.each do |n| %>
    <p class="alert alert-success"> <%= n %> </p>
  <% end %>
<% elsif notice && notice.is_a?(String) %>
  <p class="alert alert-success"> <%= notice %> </p>
<% end %>

<% if alert && alert.is_a?(Array) %>
  <% alert.each do |a| %>
    <p class="alert alert-danger"> <%= a %> </p>
  <% end %>
<% elsif alert && alert.is_a?(String) %>
  <p class="alert alert-danger"> <%= alert %> </p>
<% end %>

app/views/layouts/_follow_state.html.erb
<% if current_user.followings.include?(user) %>
  <%= button_to "Unfollow", unfollow_path(user_id: user.id), method: :delete, class:"btn btn-danger", data: {turbo: 'false'}%>
<% elsif current_user.waiting_followings.include?(user) %>
  <%= button_to "Cancel", cancel_request_path(user_id: user.id), method: :delete, class:"btn btn-secondary", data: {turbo: 'false'}%>
<% elsif current_user == user %>
<% else %>
  <%= button_to "Follow", follow_path(user_id: user.id), method: :post, class:"btn btn-primary", data: {turbo: 'false'}%>
<% end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light sticky-top bg-white border-bottom" style="border-color: #afafaf">
  <div class="container-fluid w-75">
    <%= link_to 'Railstagram' ,root_path, class: "fw-bold fs-3 text-muted", style: "text-decoration: none; font-style: oblique" %> 
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="d-flex">
      <div class="collapse navbar-collapse me-5" id="navbarSupportedContent">

      </div>

      <div class="navbar-collapse gap-4">
        <%=  link_to root_path, class: "text-dark" do %> <i class="fa-solid fa-house fa-xl"></i> <% end %>
        <i class="fa-brands fa-facebook-messenger fa-xl"></i>
        <a type="button" class="text-dark" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
          <i class="fa-regular fa-square-plus fa-xl"></i>
        </a>
        <i class="fa-regular fa-compass fa-xl"></i>
<%# ------------------------------------------------------------------------------ %>
        <div class="dropstart">
          <% if current_user.waiting_received_requests.count > 0 %>
            <i class="fa-solid fa-heart-circle-plus fa-xl" data-bs-toggle="dropdown" aria-expanded="false"></i>
            <% else %>
            <i class="fa-regular fa-heart fa-xl" data-bs-toggle="dropdown" aria-expanded="false"></i>
          <% end %>
          <% if current_user.waiting_received_requests.count > 0 %>
            <ul class="dropdown-menu p-4">
              <% current_user.waiting_received_requests.each do |fr| %>
                <li>
                  <div class="d-flex justify-content-between">
                    <div class="d-flex">
                      <%= image_tag fr.follower.profile_pic.attached? ? fr.follower.profile_pic : 'default_head.png', class: "img-thumbnail rounded-circle", style: "width: 2.5rem" %>
                      <div class="d-flex flex-column mx-3 justify-content-center">
                        <small class="fw-bold" style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;max-width:5rem"><%= link_to fr.follower, class:  "a-decoration-none" do %><%= fr.follower.user_name %><% end %></small>
                      </div>
                    </div>
                    <div class="d-flex flex-row align-items-center justify-content-between", style="width: 10.5rem">
                      <%= button_to accept_follow_path(follow_id: fr.id), method: :post, class:"btn btn-primary", style: "text-decoration:none" do %>
                        <small class="fw-bold text-white">Accept</small>
                      <% end %>
                      <%= button_to decline_follow_path(follow_id: fr.id), method: :delete, class:"btn btn-danger", style: "text-decoration:none" do %>
                        <small class="fw-bold text-white">Decline</small>
                      <% end %>
                    </div>                    
                  </div>
                </li>
              <% end %>
            </ul>
          <% end %>
        </div>
<%# ------------------------------------------------------------------------------ %>        
        <div class="dropdown">
          <a class="" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if current_user && current_user.profile_pic.attached? %>
              <%= image_tag current_user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 2rem" %>
            <% else %>
              <%= image_tag 'default_head.png', class: "img-thumbnail rounded-circle", style: "width: 2rem" %>
            <% end %>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'Profile', user_path(current_user), class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to 'Settings', edit_user_registration_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= button_to 'Log out', destroy_user_session_path, class: "dropdown-item", method: :delete%>
            </li>
          </ul>
        </div>
<%# ------------------------------------------------------------------------------ %>  
      </div>
    </div>
  </div>
</nav>

<%= render 'posts/form', post: Post.new %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railstagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/flash_messages" %>
    <% if current_user%>
      <%= render 'layouts/navbar' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<!-- Modal -->
<div class="modal fade modal-lg" id="staticBackdrop" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_with(model: post) do |form| %>
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Create new post!</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body d-flex">
          <%# Error Handler %>
          <% if post.errors.any? %>
          <div style="color: red">
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
          <ul>
            <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
          </ul>
          </div>
          <% end %>
          <%# 圖片區 %>
          <div class="border-end border-secondary mx-2" style="width:60%">
            <%= form.file_field :images, multiple: true, required: true, id: "post-images" %>
          </div>
          <%# 選單區 %>
          <div style="width:40%">
            <div class="my-2">
            <% if current_user.profile_pic.attached? %>
            <%= image_tag current_user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 10%" %>
              <% else %>
            <%= image_tag 'default_head.png', class: "img-thumbnail rounded-circle", style: "width: 10%" %>
            <% end %>
            </div>
            <div>
              <%= form.text_area :title, rows:8, placeholder: "Write some contents...", class: "form-control border-0", style:"resize:none" %>
            </div>
            <div>
              <%= form.text_field :location, placeholder: "Add location", class: "form-control" %>
            </div>
            <div class="d-flex justify-content-between align-items-center border form-control my-2" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
              <a class="text-dark"  style="text-decoration:none">
                Advanced Settings
              </a>
              <i class="fa-solid fa-chevron-down"></i>
            </div>
            <div class="collapse" id="collapseExample">
              <div class="card card-body">
                 <div class="form-check form-switch">
                    <%= form.check_box :allow_comments, class: "form-check-input", role:"switch", checked: true %>
                    <%= form.label :allow_comments, style: "display: block", class: "form-check-label" %>
                  </div>

                  <div class="form-check form-switch">
                    <%= form.check_box :show_likes_count, class: "form-check-input", role:"switch", checked: true %>
                    <%= form.label :show_likes_count, style: "display: block", class: "form-check-label"  %>
                  </div>
              </div>
            </div>
          </div>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= form.submit "Post", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_liker.html.erb
<div class="d-flex justify-content-between">
  <div class="d-flex">
    <%= image_tag liker.profile_pic.attached? ? liker.profile_pic : 'default_head.png', class: "img-thumbnail rounded-circle", style: "width: 2.5rem" %>
    <div class="d-flex flex-column mx-3 justify-content-center">
      <small class="fw-bold" style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;max-width:10rem">
        <%= link_to liker, class:  "a-decoration-none", data: {turbo: 'false'} do %>
          <%= liker.user_name %>
        <% end %>
      </small>
    </div>
  </div>

  <%# <%= render 'layouts/shared/follow_state', user: liker %>
</div>

app/views/posts/_modal_comment.html.erb
<div id="post<%=comment.post_id%>ModalComment<%=comment.id%>">
  <div class="d-flex justify-content-between">
    <div class="d-flex">
     <%= image_tag comment.user.profile_pic.attached? ? comment.user.profile_pic : 'default_head.png', class: "img-thumbnail rounded-circle", style: "width: 2.5rem; max-height:2.5rem" %>
      <div class="d-flex flex-column mx-3 justify-content-center">
        <small class="fw-bold" style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;max-width:10rem"><%= link_to "#", class:  "a-decoration-none", data: {turbo: 'false'} do %><%= comment.user.user_name %><% end %></small>
        <small > <%= comment.body %> </small>
        <small class="text-muted" > <%=  time_ago_in_words(comment.created_at)  %> </small>
      </div>
    </div>
    <% if comment.user == current_user%>
      <%= button_to comment_path(id: comment.id), method: :delete, style: "background:none; border:none " do %>
        <i class="fa fa-times"> </i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class= "my-3" id="<%= dom_id post %>">

  <div class="card" style="width: 28rem;">
    <div class="card-header bg-white d-flex justify-content-between">
      <div>
      <%= link_to post.user, class: "a-decoration-none" do %>
        <% if post.user.profile_pic.attached? %>
          <%= image_tag post.user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 10%" %>
            <% else %>
          <%= image_tag 'default_head.png', class: "img-thumbnail rounded-circle", style: "width: 10%" %>
        <% end %>
      <% end %>
        <%= link_to post.user, class: "a-decoration-none" do %>
         <span class="fw-bold mx-2"><%= post.user.user_name %></span>
        <% end %>
      </div>
      <% if current_user == post.user %>
      <div class="dropdown">
        <a class="text-dark fs-4" style="text-decoration:none" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
         ...
        </a>
        <ul class="dropdown-menu">
        <li><%= button_to 'Delete post', post, method: :delete, class:"dropdown-item" %></li>
        </ul>
      </div>
      <% end %>
    </div>
    <div class="card-body">
      <div id="post<%= post.id %>_images" class="carousel slide">
        <div class="carousel-inner">
          <% post.images.each_with_index do |image,i| %>
          <div class="carousel-item <%= i == 0? 'active' : '' %>" style="height: 25rem ">
            <%= image_tag image, class: "d-block w-100", style: "max-height: 100%; object-fit: cover;" %>
          </div>
          <% end %>
        </div>
        <% if post.images.count > 1 %>
        <button class="carousel-control-prev" type="button" data-bs-target="#post<%= post.id %>_images" data-bs-slide="prev">
          <span><i class="fa-solid fa-circle-arrow-left" aria-hidden="true"></i></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#post<%= post.id %>_images" data-bs-slide="next">
          <span><i class="fa-solid fa-circle-arrow-right" aria-hidden="true"></i></span>
          <span class="visually-hidden">Next</span>
        </button>
        <% end %>
        <div class="carousel-indicators" style="position:static">
          <% post.images.each_with_index do |img, i| %>
            <button type="button" data-bs-target="#post<%= post.id %>_images" data-bs-slide-to="<%= i %>" class=" bg-dark <%= i==0 ?  'active' : '' %>" <%= i==0 ? 'aria-current="true"' : '' %> aria-label="Slide <%= i+1 %>"></button>
          <% end %>
        </div>
      </div>

        <%= render 'posts/post_action', post: post %>

        <p class = "card-text" >
          <span class="fw-bold"><%= post.user.user_name %></span> 
          <%= post.title %>
        </p>

      <%= render 'posts/post_comments', post: post%>

      <small class="text-muted"><%= time_ago_in_words(post.created_at) %></small>
    </div>
    <%= form_with url: comments_path, method: :post, data: {controller: "comments", action: "turbo:submit-end->comments#clear"} do |f| %>
      <div class="card-footer d-flex justify-content-between bg-white">
        <%= f.hidden_field :post_id, value: post.id %>
        <%= f.text_area :comment_body, class: "w-75", placeholder: "Add a comment...", style:"border:none" %>
        <%= f.submit "Post", class: "text-primary fw-bold", style: "background:none;border:none"  %>
      </div>
    <% end %>
  </div>


</div>

app/views/posts/_post_action.html.erb
<%= turbo_frame_tag "post#{post.id}actions" do %>
  <div class="d-flex justify-content-start align-items-center gap-1 mb-3">
    <%= button_to toggle_like_path(post_id: post.id), method: :post, style: "border:none; background:none", id: "post#{post.id}actions-likeBtn" do %>
      <i class="<%= post.likes.find_by(user: current_user) ? "fa-solid color-red" : "fa-regular" %> fa-heart fa-xl"></i>
    <% end %>
    <a href="#" data-bs-toggle="modal" data-bs-target="#post<%= post.id %>_commentsModal" style="text-decoration:none" >
      <i class="fa-regular fa-comment fa-xl fa-flip-horizontal text-dark"> </i>
    </a>
  </div>
  <a href="#" data-bs-toggle="modal" data-bs-target="#post<%= post.id %>_likesModal" style="text-decoration:none" class="text-dark">
    <% if post.likes.count > 0 %>
    <small class="fw-bold my-1"><%= pluralize(post.likes.count, "like") %> </small>
    <% end %>
  </a>

  <%# 跳出視窗(bootstrap modal) %>
  <div class="modal fade" id="post<%= post.id %>_likesModal" tabindex="-1" aria-labelledby="post<%= post.id %>_likesModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="post<%= post.id %>_likesModalLabel">Post Likes</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="d-flex flex-column gap-3" >
            <% post.likers.each do |liker| %>
              <%= render "posts/liker", liker: liker %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/posts/_post_comments.html.erb
<%= turbo_frame_tag "post#{post.id}comments" do %>
  <% if post.comments.count > 0 %>
    <a href="#" data-bs-toggle="modal" data-bs-target="#post<%= post.id %>_commentsModal" style="text-decoration:none" >
      <small class="text-muted">View all <%= pluralize(post.comments.count, "comments") %> </small>
    </a>
  <% end %>
  <% post.comments.last(5).each do |comment| %>
    <p class="card-text m-0"> <%= link_to comment.user, class: "a-decoration-none", data: {turbo: 'true'} do %> <span class="fw-bold"><%= comment.user.user_name %></span><% end %> <%= comment.body %> </p>
  <% end %>


  <%# 跳出視窗(bootstrap modal) %>
  <div class="modal fade" id="post<%= post.id %>_commentsModal" tabindex="-1" aria-labelledby="post<%= post.id %>_commentsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="post<%= post.id %>_commentsModalLabel">Post Comments</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="d-flex flex-column gap-3" >
            <% post.comments.each do |comment| %>
              <%= render "posts/modal_comment", comment: comment %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<div class = "d-flex justify-content-center mt-4">
<%= render @post %>
</div>

app/views/story/_story.html.erb
<div class="d-flex flex-column justify-content-center align-items-center">
  <%= image_tag 'default_head.png', class: "img-thumbnail rounded-circle border border-2 border-primary", style: "width: 3.5rem" %>
  <small style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;max-width: 3.5rem">Username is musta</small>
</div>

app/views/story/_story_list.html.erb
<div class="card d-flex flex-row align-items-center gap-3 px-3" style="width: 28rem; height: 7rem; overflow-x:scroll;" >
  <% (0...7).each do %>
    <%= render "story/story" %>
  <% end %>
</div>

app/views/users/_user_private.html.erb
<div class="container bg-white border text-center p-5">
  <p>This account is private </p>
  <p> Follow this account to see their photos </p>
<div>